---
title: "Load data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(magrittr)
```

```{r}

data_summary <- function(data, varname, groupnames, ci = TRUE){
   length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

  data_sum <- data %>% group_by(.dots = groupnames) %>% summarise(N = length2(get(varname)), mean = mean(get(varname), na.rm = TRUE), sd = sd(get(varname), na.rm = TRUE)) %>% rename(!!varname := mean)
  

  if(ci==FALSE){
    return(data_sum)
  }
  else{
    data_sum$se <- data_sum$sd / sqrt(data_sum$N)

  ciMult <- qt(0.95/2 + .5, data_sum$N-1)
  data_sum$ci <- data_sum$se * ciMult
 return(data_sum)
  }
}

```

## Loading in the data from trained models

```{r, cache=TRUE}

## No need to run this if you already have the dataframe for pre and post

fdir <- '/Users/Debasmita/Desktop/RNN-Priming/' #directory where all the models and test files are
csize <- c(80) #80
nhid <- c(400) #650
clist <- c('a', 'b', 'c', 'd', 'e')
testlist <- c(6)
#testlist <- c(6:10)
testtype <- c('adjunct', 'wh', 'subject', 'object', 'leftbranch', 'coordstruct', 'complexnp', 'bridge')
testtype <- c('nonwh','linkedwh')
#testtype <- c('bridge','object', 'coordstruct')
#testtype2 <- c('adjunct', 'wh', 'subject', 'leftbranch', 'complexnp')
amts <- c(20)



#csize_clist_nhid.testlist.testtype.testtype.post #adapted to the first type, tested on the second type
#csize_clist_nhid.testlist..testtype.pre #original model tested on one constr.pre
  
#pre_list <- as.list(seq_len(5250))
pre_list <- as.list(seq_len(2))
#post_list <- as.list(seq_len(36750))
post_list <- as.list(seq_len(4))
pre_ind <- 1
post_ind <- 1
for(cl in clist) {
  for(tl in testlist){
    #curr_fdir <- paste(fdir,cl,tl,'/', sep = '')
    curr_fdir <- paste(fdir, sep = '')
    for(amt in amts) {
      for(cs in csize){
        for(nh in nhid) {
          for(tt in testtype){
            pre_fname <- (paste(curr_fdir, tt, '_', cl, '_test_results.csv', sep = '')) #tests w original
            # print(pre_fname)
            # print(pre_ind)
            curr <- read.table(pre_fname, header = TRUE, quote = '') #USE THIS LINE !!
            curr$csize <- cs
            curr$clist <- cl
            curr$nhid <- nh
            curr$adaptlist <- tl
            curr$pre_test <- tt
            curr$amt <- amt
            colnames(curr)[colnames(curr)=="surp"] <- "pre_surp"
            colnames(curr)[colnames(curr)=="entropy"] <- "pre_entropy"
            colnames(curr)[colnames(curr)=="entred"] <- "pre_entred"
            pre_list[[pre_ind]] <- curr
            pre_ind <- pre_ind+1
            
            for(tt2 in testtype){
              post_fname <- (paste(curr_fdir, 'shuffled_', tt2, '_', tt, '_', cl, '.csv', sep = '')) #tests with adapted
              #print(post_fname)
              curr <- read.table(post_fname, header = TRUE, quote = '')
              curr$csize <- cs
              curr$clist <- cl
              curr$nhid <- nh
              curr$adaptlist <- tl
              curr$adapt <- tt2
              curr$amt <- amt
              curr$post_test <- tt
              colnames(curr)[colnames(curr)=="surp"] <- "post_surp"
              colnames(curr)[colnames(curr)=="entropy"] <- "post_entropy"
              colnames(curr)[colnames(curr)=="entred"] <- "post_entred"
              post_list[[post_ind]] <- curr
              post_ind <- post_ind+1
            }
          }
        }
      }
    }
  }
}

```


```{r}

## No need to run this if you already have dataframe for pre and post

pre <- do.call(rbind, pre_list)
post <- do.call(rbind, post_list)

pre <- pre[(pre$pre_test=='nonwh')&(pre$sentpos>0) | (pre$pre_test=='linkedwh')&(pre$sentpos > 1),]


saveRDS(pre, '../shuffled_link_pre_list.Rda')
saveRDS(post, '../shuffled_link_post_list.Rda')

```

### With unks
```{r, cache=TRUE}

pre <- readRDS('../shuffled_link_pre_list.Rda')
post <- readRDS('../shuffled_link_post_list.Rda')

pre_summary <- data_summary(pre, 'pre_surp', quos(sentid, csize, clist, nhid, adaptlist, pre_test, amt))

post_summary <- data_summary(post, 'post_surp', quos(sentid, csize, clist, nhid, adaptlist, post_test, amt, adapt))

saveRDS(pre, '../shuffled_link_pre_list_summary.Rda')
saveRDS(post, '../shuffled_link_post_list_summary.Rda')

```


### Without unks

```{r, cache=TRUE}

pre_summary_no.unk <- data_summary(subset(pre, word != '<unk>'), 'pre_surp', quos(sentid, csize, clist, nhid, adaptlist, pre_test, amt))

post_summary_no.unk <- data_summary(subset(post, word != '<unk>'), 'post_surp', quos(sentid, csize, clist, nhid, adaptlist, post_test, amt, adapt))

saveRDS(pre_summary_no.unk, '../shuffled_link_pre_list_summary_no.unk.Rda')
saveRDS(post_summary_no.unk, '../shuffled_link_post_list_summary_no.unk.Rda')
#filler gaps stop here

```


## Loading in the data from untrained randomly initialized models

```{r}


#testlist <- c(1:10)
testlist <- c(6:10)
nhid <- c(100, 200, 400, 800, 1600)
testtype <- c('ocont','orc','orrc','prc','prrc','scont','src')
seeds <- c(5, 7, 17, 81, 109)

zero_pre_list <- as.list(seq_len(350))
zero_post_list <- as.list(seq_len(2450))

pre_ind <- 1
post_ind <- 1

# nhid.list.seed.adapt.test.post   OR   nhid.list.seed..test.pre

fdir <- '../data/untrained_model_surprisal/'

for(s in seeds){
  for(tl in testlist){
    for(nh in nhid) {
       for(tt in testtype){
            pre_fname <- (paste(fdir,nh, '.', tl, '.', s,  '..', tt, '.pre', sep = ''))
            if(!file.exists(pre_fname)) {
              print(pre_fname)
            }
            curr <- read.table(pre_fname, header = TRUE, quote = '')
            curr$nhid <- nh
            curr$adaptlist <- tl
            curr$pre_test <- tt
            curr$seed <- s
            colnames(curr)[colnames(curr)=="surp"] <- "pre_surp"
            colnames(curr)[colnames(curr)=="entropy"] <- "pre_entropy"
            colnames(curr)[colnames(curr)=="entred"] <- "pre_entred"
            zero_pre_list[[pre_ind]] <- curr
            pre_ind <- pre_ind+1
            
            for(tt2 in testtype){
              post_fname <- (paste(fdir, nh, '.', tl, '.', s, '.', tt2, '.', tt, '.post', sep = ''))
              if(!file.exists(post_fname)) {
                print(post_fname)
              }
              curr <- read.table(post_fname, header = TRUE, quote = '')
              curr$nhid <- nh
              curr$adaptlist <- tl
              curr$adapt <- tt2
              curr$post_test <- tt
              curr$seed <- s
              colnames(curr)[colnames(curr)=="surp"] <- "post_surp"
              colnames(curr)[colnames(curr)=="entropy"] <- "post_entropy"
              colnames(curr)[colnames(curr)=="entred"] <- "post_entred"
              zero_post_list[[post_ind]] <- curr
              post_ind <- post_ind+1
            }
          }
        }
      }
}

```


```{r}

pre_zero <- do.call(rbind, zero_pre_list)
post_zero <- do.call(rbind, zero_post_list)

```


```{r}

pre_summary_zero <- data_summary(pre_zero, 'pre_surp', .(sentid, nhid, adaptlist, pre_test, seed))

post_summary_zero <- data_summary(post_zero, 'post_surp', .(sentid,  nhid, adaptlist, post_test, adapt, seed))


pre_summary_zero_no.unk <- data_summary(subset(pre_zero, word != '<unk>'), 'pre_surp', .(sentid, nhid, adaptlist, pre_test, seed))

post_summary_zero_no.unk <- data_summary(subset(post_zero, word != '<unk>'), 'post_surp', .(sentid,  nhid, adaptlist, post_test, adapt, seed))


saveRDS(pre_summary_zero, '../data/dataframes/pre_summary_zero.Rda')
saveRDS(post_summary_zero, '../data/dataframes/post_summary_zero.Rda')

saveRDS(pre_summary_zero_no.unk, '../data/dataframes/pre_summary_zero_nounk.Rda')
saveRDS(post_summary_zero_no.unk, '.../data/dataframes/post_summary_zero_nounk.Rda')

```


